### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by a-detiste** [ttyborg/erampage#36]
thanks for keeping this alive :smile:

```
make: *** No rule to make target 'source/jaudiolib/include/fx_man.h', needed by 'obj/game.o'.  Stop.
```

I'll add this game to Debian's `game-data-packager`
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787236

**Comment by ghost** [comment]
Same here. Trying to build this on Fedora 23 and got the same error:

> make: **\* No rule to make target 'source/jaudiolib/include/fx_man.h', needed by 'obj/game.o'.  Stop.

**Comment by Chambers3000** [comment]
Also confirmed on FC24 make: **\* No rule to make target 'source/jaudiolib/include/fx_man.h', needed by 'obj/game.o'.  Stop.

**Comment by pizzadude** [comment]
It builds under an Ubuntu 12.04 chroot if I do

`git revert --no-commit 441c30f9034e..HEAD`

`make`

**Comment by pizzadude** [comment]
Here's my build in case anyone wants it.

Built on Ubuntu 12.04 chroot.

Confirmed running on Linux Mint 18 AKA Ubuntu 16.04 64-bit

http://pizzadude.ca/builds-linux/erampage.tar.xz
